version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
    - ./frontend_common:/app/frontend_common    
